# This file will hold any hard configurations MailCannon may need. Customizations included.

# When creating a MailCannon::Envelope the default behavior is to auto-post the Job to send it.
auto_post: true

# This is will schedule a delay for the Job execution, useful if you want to be able to Cancel the Job.
waiting_time: 0

# Destroy mail content after send was successful, all other Envelope data is left untouched.
# * this config is useful for saving storage
auto_destroy: true

# MailCannon builds the 'name' substitution Array for convenience, using the name from Envelope.to: [{email: 'foo', name: 'bar'}]
default_name_placeholder: "*|NAME|*"

# MailCannon builds the 'email' substitution Array for convenience, using the email from Envelope.to: [{email: 'foo', name: 'bar'}]
default_email_placeholder: "*|EMAIL|*"